apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::854462094389:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::854462094389:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1LUVUFSJRW5V3
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-25T13:18:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1289"
  uid: e0147118-8247-41e1-a148-5d0789bff22b
