apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::854462094389:role/UdacityFlaskDeployCBKubectlRole
      username: build    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::854462094389:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KX22D5VFGFHG
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-24T04:58:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1332"
  uid: d7909244-78dd-45b8-83dd-75c99703bac9
