apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::854462094389:role/UdacityFlaskDeployCBKubectlRole
      username: build    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::854462094389:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-L8AQHVFAUNF0
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-23T10:07:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1268"
  uid: 12644dce-8266-44d4-8a0d-632ece1d33aa
